#version: '3'

services:
  nginx:
    container_name: back-end-nginx
    build:
      context: ./
      dockerfile: docker/nginx.Dockerfile
    ports:
      - "80:80"
    volumes:
      - "./nginx_conf/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx_conf/sites-enabled:/etc/nginx/conf.d/"
    networks:
      - backend-app
    depends_on:
      - app

  app:
    container_name: back-end-app
    build:
      context: ./
      dockerfile: docker/app.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "./:/www/apps/backend/"
    networks:
      backend-app:
        aliases:
          - backend.app.loc
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    container_name: app_redis
    ports:
      - "16379:6379"
    command: redis-server --requirepass secret
    networks:
      backend-app:
        aliases:
          - redis

networks:
  backend-app:
    driver: bridge
